# Generated by Django 4.0.3 on 2022-04-07 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
