# Generated by Django 4.0.3 on 2022-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
